development:
  adapter: postgresql
  database: cv2_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: cv2_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cv2_production
  pool: 5
  timeout: 5000
